### ISSUE TITLE
Obsolete form for adding Newgrf to bananas.openttd.org

### ISSUE THREAD

**Issue by agentw4b** [OpenTTD/infrastructure#2]
The latest version of Openttd that can be selected on the form is version 1.6.0
![bananas](https://user-images.githubusercontent.com/38394751/57433447-ce83f400-7238-11e9-908e-2107c61c2d8d.png)

**Comment by TrueBrain** [comment]
This has been resolved by replacing BaNaNaS with a new version, which made the version a free field. Means people can also do some predictive versioning, if they so like.
